############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2



[[main]]
name = "Investigation"
url = "investigation/post-1/"
weight = 3

[[main]]
weight = 4
name = "Pages"
hasChildren = true


 

  [[main]]
  parent = "Pages"
  name = "Blog"
  url = "https://medium.com/hornet-technology"
  weight = 1

 

 

 

 

  [[main]]
  parent = "Pages"
  name = "Privacy Policy"
  url = "privacy-policy/"
  weight = 2

 


  
[[main]]
name = "Demo"
url = "demo/"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "https://medium.com/hornet-technology"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

