#################### default parameters ################################
# favicon
favicon = "images/faviconn.png"
# logo
logo = "images/hornet-h1.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "170px"
# if logo_webp set false, it will not generate WEBP version of logo
logo_webp = true # default is true
# logo text will only show when logo is missing.
logo_text = "Hornet"

# footer information
footer_info = "Hornet is India's First DarkWeb and Blockchain Investigation and Intelligence Platform."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# career form action
career_form_action = "#" # career form works with https://formspree.io

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# Main Sections
mainSections= ["blog"]

# contact information
[contact_info]
address = "Room No 30, Unit No 11W2, 11th Floor Mani Casadona, Newtown, Action Area IIF/04, Street No 372, Kolkata 700161"
phone = ["+913348134365"]
email = ["souvikh@hornet.technology","subhrom@hornet.technology"]

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Login"
link = "https://www.hornet.technology/login"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Hugo", "GetHugoThemes", "Themefisher"]
description = "Software and SAAS Landing Hugo Theme"
author = "Gethugothemes"
image = "images/og-image.jpg" # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = "" # your username

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code
facebook = "" # Your verification code

# Crisp Chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"



############################# social site ########################
[[social]]
title = "facebook"
icon = "lab la-instagram" # https://icons8.com/line-awesome
link = "https://www.instagram.com/hornet.technology/"

[[social]]
title = "twitter"
icon = "lab la-twitter" # https://icons8.com/line-awesome
link = "https://twitter.com/hornetdefiant"

[[social]]
title = "linkedin"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "https://www.linkedin.com/company/hornet.technology/"

